# Generated by Django 3.2.9 on 2021-11-28 02:51

import uuid

import django.db.models.deletion
from django.db import migrations, models

import analytics.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserCookie',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.usercookie')),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('duration', models.DurationField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.page')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.session')),
            ],
        ),
        migrations.CreateModel(
            name='MouseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('clicked', models.PositiveSmallIntegerField(blank=True,
                                                             choices=[(analytics.models.MouseAction.Button['LEFT'], 1),
                                                                      (
                                                                      analytics.models.MouseAction.Button['MIDDLE'], 2),
                                                                      (
                                                                      analytics.models.MouseAction.Button['RIGHT'], 3)],
                                                             null=True)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.pageview')),
            ],
        ),
    ]
