# Generated by Django 3.2.9 on 2021-11-28 03:24

import uuid

import django.db.models.deletion
from django.db import migrations, models

import analytics.models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mouseaction',
            name='clicked',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(analytics.models.MouseAction.Button['LEFT'], 1),
                                                            (analytics.models.MouseAction.Button['MIDDLE'], 2),
                                                            (analytics.models.MouseAction.Button['RIGHT'], 3)],
                                                   editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='mouseaction',
            name='time',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='mouseaction',
            name='view',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                    to='analytics.pageview'),
        ),
        migrations.AlterField(
            model_name='mouseaction',
            name='x',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='mouseaction',
            name='y',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='complete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='duration',
            field=models.DurationField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='page',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='analytics.page'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='session',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                    to='analytics.session'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                    to='analytics.usercookie'),
        ),
        migrations.AlterField(
            model_name='usercookie',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
