# Generated by Django 3.2.9 on 2021-11-28 04:09

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0002_auto_20211128_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouseaction',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), editable=False),
        ),
    ]
