# Generated by Django 3.2.9 on 2021-11-28 09:03

from django.db import migrations, models

import analytics.models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0003_auto_20211128_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercookie',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mouseaction',
            name='clicked',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(analytics.models.MouseAction.Button['UNDEFINED'], 0),
                                                            (analytics.models.MouseAction.Button['LEFT'], 1),
                                                            (analytics.models.MouseAction.Button['MIDDLE'], 2),
                                                            (analytics.models.MouseAction.Button['RIGHT'], 3)],
                                                   editable=False, null=True),
        ),
    ]
