# Generated by Django 3.2.9 on 2021-11-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0004_auto_20211128_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
