# Generated by Django 3.2.9 on 2021-11-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0005_pageview_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='ip_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
