# Generated by Django 3.2.9 on 2021-11-28 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0006_pageview_ip_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='ip_address',
        ),
    ]
