# Generated by Django 3.2.9 on 2021-11-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0007_remove_pageview_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='end_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
