# Generated by Django 3.2.9 on 2021-11-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0008_pageview_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
