# Generated by Django 3.2.9 on 2021-11-28 13:18

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0009_alter_pageview_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), editable=False),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='end_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
