# Generated by Django 3.2.9 on 2021-11-28 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0010_auto_20211128_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
    ]
