# Generated by Django 3.2.9 on 2021-11-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0011_remove_session_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
