# Generated by Django 3.2.9 on 2021-11-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0012_alter_pageview_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercookie',
            name='user_agent',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
