"""
Django settings for travel_website project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import re
from pathlib import Path
from random import random

import environ
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from .middleware import CacheControlMiddleware
import openai

env = environ.Env(
    DEBUG=(bool, False),
    PRODUCTION=(bool, False),
    SENTRY=(bool, True),
    CLOUDFLARE_API_TOKEN=(str, None),
    CLOUDFLARE_ZONE_ID=(str, None),
    CLOUDFLARE_DOMAIN=(str, None),
    NOCACHE=(bool, False),
    NO_CACHE_INVALIDATION=(bool, False),
    HCAPTCHA_SITEKEY=(str, None),
    HCAPTCHA_SECRET=(str, None),
    STRIPE_PUBLIC_KEY=(str, None),
    STRIPE_SECRET_KEY=(str, None),
    ZOHO_PASSWORD=(str, None),
    OPENAI_API_KEY=(str, None),
    ADMIN_EMAIL=(str, 'admin@saigatours.com'),
)
environ.Env.read_env()

CLOUDFLARE_API_TOKEN = env('CLOUDFLARE_API_TOKEN')
CLOUDFLARE_ZONE_ID = env('CLOUDFLARE_ZONE_ID')
CLOUDFLARE_DOMAIN = env('CLOUDFLARE_DOMAIN')
NOCACHE = env('NOCACHE')
NO_CACHE_INVALIDATION = env('NO_CACHE_INVALIDATION')

OPENAI_API_KEY = env('OPENAI_API_KEY')
openai.api_key = OPENAI_API_KEY

if env('SENTRY'):
    SENTRY_PROJECT = env('SENTRY_PROJECT')
    sentry_sdk.init(
        dsn=SENTRY_PROJECT,
        integrations=[DjangoIntegration()],
        traces_sample_rate=1.0,
        send_default_pii=True,
    )

PRODUCTION = env('PRODUCTION')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default='django-insecure-+c1*+&n&%r5=)lirl@$3s415*!n%3!(w@^d7kg!!^*in3f7m%f')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
    }
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
ADMINS = [('Admin', 'admin@saigatours.com')]
MANAGERS = [('Admin', 'admin@saigatours.com')]

ALLOWED_HOSTS = ["coolwebsite.pythonanywhere.com", "127.0.0.1", "www.saigatours.com", "saigatours.com", "admin.saigatours.com", 'localhost', '192.168.1.16', 'testing.saigatours.com']

# Application definition

INSTALLED_APPS = [
    'customers',
    'admin_interface',
    'job_queue',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
    "django_unused_media",
    'ckeditor',
    'ckeditor_uploader',
    'django_bootstrap5',
    'mathfilters',
    'simple_history',
    'colorfield',
    'analytics',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'silk',
    'django_countries',
    'hcaptcha_field',
    'nested_admin',
    'vectordb',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'two_factor',
    'two_factor.plugins.webauthn',
    'hijack',
    'hijack.contrib.admin',
]

SITE_ID = 1


MIDDLEWARE = [
    'django.middleware.common.BrokenLinkEmailsMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'silk.middleware.SilkyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'travel_website.middleware.CacheControlMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'customers.middleware.Enforce2FAForAdminsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    # 'travel_website.middleware.StatsMiddleware',
    'main.middleware.CacheForUsers',
    'hijack.middleware.HijackUserMiddleware',
]

if DEBUG:
    INSTALLED_APPS += ['livereload']
    MIDDLEWARE += ['livereload.middleware.LiveReloadScript']

ROOT_URLCONF = 'travel_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'main/templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.views.global_context',
                'analytics.analytics_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'travel_website.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env("DATABASE_NAME"),
        'HOST': env("DATABASE_HOST"),
        'USER': env("DATABASE_USER"),
        'PASSWORD': env("DATABASE_PASSWORD"),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'assets'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CACHE_ROOT = BASE_DIR / 'cached_pages'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = '587'
#EMAIL_USE_TLS = True
#EMAIL_HOST_USER = 'duncrob99@gmail.com'
#EMAIL_HOST_PASSWORD = 'uopqavdbzsvdivxg'
#SERVER_EMAIL = 'duncrob99@gmail.com'
#DEFAULT_FROM_EMAIL = 'duncrob99@gmail.com'

EMAIL_HOST = 'smtp.zoho.com.au'
EMAIL_PORT = '587'
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'admin@saigatours.com'
EMAIL_HOST_PASSWORD = env("ZOHO_PASSWORD")
SERVER_EMAIL = 'admin@saigatours.com'
DEFAULT_FROM_EMAIL = 'admin@saigatours.com'
ADMIN_EMAIL = env("ADMIN_EMAIL")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_UPLOAD_PATH = 'media/ckeditor/images'

DJANGO_WYSIWYG_FLAVOR = "ckeditor"
# CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'
CKEDITOR_RESTRICT_BY_USER = True  # Only who upload image see it
CKEDITOR_BROWSE_SHOW_DIRS = True  # Shows directory of image in the server
CKEDITOR_RESTRICT_BY_DATE = True  # Arranges image in terms of date uploaded
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
        'extraPlugins': 'codesnippet, splitsection',
        'skin': 'moono-lisa',
        'removePlugins': 'exportpdf'
    },
}

APPEND_SLASH = True

X_FRAME_OPTIONS = 'SAMEORIGIN'
SILENCED_SYSTEM_CHECKS = ['security.W019']

FIXTURE_DIRS = (
    BASE_DIR / 'fixtures',
)

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Store session cookie for as long as possible
SESSION_COOKIE_SECURE = not DEBUG
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365 * 1000  # 1000 years


SILKY_IGNORE_PATHS = [
    r'^/admin/',
    r'^/static/',
    r'^/stats/',
]

SILK_CHECK_PERCENT = 10

def should_intercept(request):
    # Don't intercept if path is in the list of ignored paths
    for ignored_path in SILKY_IGNORE_PATHS:
        if re.match(ignored_path, request.path):
            return False

    if DEBUG:
        return True
    else:
        return random() < SILK_CHECK_PERCENT / 100


SILKY_PYTHON_PROFILER = True
SILKY_PYTHON_PROFILER_BINARY = True
SILKY_META = True
SILKY_MAX_RECORDED_REQUESTS = 10000
SILKY_MAX_RECORDED_REQUESTS_CHECK_PERCENT = 5
SILKY_AUTHENTICATION = True
SILKY_AUTHORISATION = True
SILKY_INTERCEPT_FUNC = should_intercept
SILK_MAX_RESPONSE_BODY_SIZE = 1024

# countries settings
COUNTRIES_FLAG_URL = STATIC_URL + 'flags/{code}.gif'
COUNTRIES_FIRST = [
    'AU',
    'US',
    'GB',
    'FR',
    'ME',
    'CA',
    'NL',
    'KZ',
    'IN',
    'IE'
]
# COUNTRIES_FIRST_REPEAT = True
# COUNTRIES_FIRST_BREAK = "-----------------"

if DEBUG:
    try:
        import nplusone
        nplusone.show_nplusones()
    except ImportError:
        print("nplusone not installed")


if env('HCAPTCHA_SITEKEY') and env('HCAPTCHA_SECRET'):
    HCAPTCHA_SITEKEY = env("HCAPTCHA_SITEKEY")
    HCAPTCHA_SECRET = env("HCAPTCHA_SECRET")

STRIPE_PUBLIC_KEY = env("STRIPE_PUBLIC_KEY")
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY")

LOGIN_URL = 'two_factor:login'
LOGIN_REDIRECT_URL = 'dashboard'

TWO_FACTOR_WEBAUTHN_RP_NAME = 'SAIGA Tours'
HIJACK_PERMISSION_CHECK = "hijack.permissions.superusers_and_staff"

DJANGO_VECTOR_DB = {
    "LOAD_EMBEDDING_MODEL_ON_STARTUP": not DEBUG,
}
