# Generated by Django 3.2.9 on 2023-03-13 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20230312_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formtask',
            options={'ordering': ['due']},
        ),
        migrations.AddField(
            model_name='filledform',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='completed_forms', to='customers.formtask'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('file', 'File'), ('countries', 'Countries'), ('date', 'Date'), ('number', 'Number'), ('email', 'Email'), ('url', 'URL'), ('tel', 'Telephone')], max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='filledform',
            unique_together={('customer', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='filledformfield',
            unique_together={('form', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('section', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='formfieldoption',
            unique_together={('field', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='formsection',
            unique_together={('form', 'title')},
        ),
        migrations.RemoveField(
            model_name='filledform',
            name='form',
        ),
    ]
