# Generated by Django 3.2.9 on 2023-03-15 03:42

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20230313_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filledformfield',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=customers.models.FilledFormField.upload_location),
        ),
    ]
