# Generated by Django 3.2.9 on 2023-03-15 04:14

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_filledformfield_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filledformfield',
            name='file',
            field=models.FileField(blank=True, max_length=511, null=True, upload_to=customers.models.FilledFormField.upload_location),
        ),
    ]
