# Generated by Django 3.2.9 on 2023-03-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_filledformfield_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='signature_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
